apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: censorhub

resources:
  - ../base
  - ingress.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: censorhub
      spec:
        replicas: 3
        template:
          spec:
            containers:
              - name: censorhub
                resources:
                  requests:
                    cpu: "500m"
                    memory: "256Mi"
                  limits:
                    cpu: "2000m"
                    memory: "1Gi"
                env:
                  - name: APP_ENV
                    value: "production"
                  - name: CENSORHUB_DATABASE_DSN
                    valueFrom:
                      secretKeyRef:
                        name: censorhub-secrets
                        key: database-dsn
                  - name: CENSORHUB_REDIS_ADDR
                    valueFrom:
                      secretKeyRef:
                        name: censorhub-secrets
                        key: redis-addr
                  - name: CENSORHUB_REDIS_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: censorhub-secrets
                        key: redis-password

  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: censorhub
      spec:
        minReplicas: 3
        maxReplicas: 20
