// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: api/proto/censor/v1/censor.proto

package censorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CensorService_Detect_FullMethodName      = "/censor.v1.CensorService/Detect"
	CensorService_Replace_FullMethodName     = "/censor.v1.CensorService/Replace"
	CensorService_BatchDetect_FullMethodName = "/censor.v1.CensorService/BatchDetect"
)

// CensorServiceClient is the client API for CensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CensorServiceClient interface {
	Detect(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
	Replace(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error)
	BatchDetect(ctx context.Context, in *BatchFilterRequest, opts ...grpc.CallOption) (*BatchFilterResponse, error)
}

type censorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCensorServiceClient(cc grpc.ClientConnInterface) CensorServiceClient {
	return &censorServiceClient{cc}
}

func (c *censorServiceClient) Detect(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, CensorService_Detect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censorServiceClient) Replace(ctx context.Context, in *FilterRequest, opts ...grpc.CallOption) (*FilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterResponse)
	err := c.cc.Invoke(ctx, CensorService_Replace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *censorServiceClient) BatchDetect(ctx context.Context, in *BatchFilterRequest, opts ...grpc.CallOption) (*BatchFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchFilterResponse)
	err := c.cc.Invoke(ctx, CensorService_BatchDetect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CensorServiceServer is the server API for CensorService service.
// All implementations must embed UnimplementedCensorServiceServer
// for forward compatibility.
type CensorServiceServer interface {
	Detect(context.Context, *FilterRequest) (*FilterResponse, error)
	Replace(context.Context, *FilterRequest) (*FilterResponse, error)
	BatchDetect(context.Context, *BatchFilterRequest) (*BatchFilterResponse, error)
	mustEmbedUnimplementedCensorServiceServer()
}

// UnimplementedCensorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCensorServiceServer struct{}

func (UnimplementedCensorServiceServer) Detect(context.Context, *FilterRequest) (*FilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Detect not implemented")
}
func (UnimplementedCensorServiceServer) Replace(context.Context, *FilterRequest) (*FilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Replace not implemented")
}
func (UnimplementedCensorServiceServer) BatchDetect(context.Context, *BatchFilterRequest) (*BatchFilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDetect not implemented")
}
func (UnimplementedCensorServiceServer) mustEmbedUnimplementedCensorServiceServer() {}
func (UnimplementedCensorServiceServer) testEmbeddedByValue()                       {}

// UnsafeCensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CensorServiceServer will
// result in compilation errors.
type UnsafeCensorServiceServer interface {
	mustEmbedUnimplementedCensorServiceServer()
}

func RegisterCensorServiceServer(s grpc.ServiceRegistrar, srv CensorServiceServer) {
	// If the following call panics, it indicates UnimplementedCensorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CensorService_ServiceDesc, srv)
}

func _CensorService_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensorServiceServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensorService_Detect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensorServiceServer).Detect(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensorService_Replace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensorServiceServer).Replace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensorService_Replace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensorServiceServer).Replace(ctx, req.(*FilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CensorService_BatchDetect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CensorServiceServer).BatchDetect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CensorService_BatchDetect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CensorServiceServer).BatchDetect(ctx, req.(*BatchFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CensorService_ServiceDesc is the grpc.ServiceDesc for CensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "censor.v1.CensorService",
	HandlerType: (*CensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Detect",
			Handler:    _CensorService_Detect_Handler,
		},
		{
			MethodName: "Replace",
			Handler:    _CensorService_Replace_Handler,
		},
		{
			MethodName: "BatchDetect",
			Handler:    _CensorService_BatchDetect_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/censor/v1/censor.proto",
}
