// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/censor/v1/censor.proto

package censorv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_censor_v1_censor_proto_rawDescGZIP(), []int{0}
}

func (x *FilterRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Original      string                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`
	Filtered      string                 `protobuf:"bytes,2,opt,name=filtered,proto3" json:"filtered,omitempty"`
	IsHit         bool                   `protobuf:"varint,3,opt,name=is_hit,json=isHit,proto3" json:"is_hit,omitempty"`
	HitCount      int32                  `protobuf:"varint,4,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	Matches       []*MatchItem           `protobuf:"bytes,5,rep,name=matches,proto3" json:"matches,omitempty"`
	RiskLevel     int32                  `protobuf:"varint,6,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	CostMs        int64                  `protobuf:"varint,7,opt,name=cost_ms,json=costMs,proto3" json:"cost_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_censor_v1_censor_proto_rawDescGZIP(), []int{1}
}

func (x *FilterResponse) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *FilterResponse) GetFiltered() string {
	if x != nil {
		return x.Filtered
	}
	return ""
}

func (x *FilterResponse) GetIsHit() bool {
	if x != nil {
		return x.IsHit
	}
	return false
}

func (x *FilterResponse) GetHitCount() int32 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *FilterResponse) GetMatches() []*MatchItem {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *FilterResponse) GetRiskLevel() int32 {
	if x != nil {
		return x.RiskLevel
	}
	return 0
}

func (x *FilterResponse) GetCostMs() int64 {
	if x != nil {
		return x.CostMs
	}
	return 0
}

type MatchItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"`
	EndPosition   int32                  `protobuf:"varint,3,opt,name=end_position,json=endPosition,proto3" json:"end_position,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchItem) Reset() {
	*x = MatchItem{}
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchItem) ProtoMessage() {}

func (x *MatchItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchItem.ProtoReflect.Descriptor instead.
func (*MatchItem) Descriptor() ([]byte, []int) {
	return file_api_proto_censor_v1_censor_proto_rawDescGZIP(), []int{2}
}

func (x *MatchItem) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *MatchItem) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *MatchItem) GetEndPosition() int32 {
	if x != nil {
		return x.EndPosition
	}
	return 0
}

func (x *MatchItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MatchItem) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type BatchFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchFilterRequest) Reset() {
	*x = BatchFilterRequest{}
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchFilterRequest) ProtoMessage() {}

func (x *BatchFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchFilterRequest.ProtoReflect.Descriptor instead.
func (*BatchFilterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_censor_v1_censor_proto_rawDescGZIP(), []int{3}
}

func (x *BatchFilterRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type BatchFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*FilterResponse      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	HitNum        int32                  `protobuf:"varint,3,opt,name=hit_num,json=hitNum,proto3" json:"hit_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchFilterResponse) Reset() {
	*x = BatchFilterResponse{}
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchFilterResponse) ProtoMessage() {}

func (x *BatchFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_censor_v1_censor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchFilterResponse.ProtoReflect.Descriptor instead.
func (*BatchFilterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_censor_v1_censor_proto_rawDescGZIP(), []int{4}
}

func (x *BatchFilterResponse) GetResults() []*FilterResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchFilterResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BatchFilterResponse) GetHitNum() int32 {
	if x != nil {
		return x.HitNum
	}
	return 0
}

var File_api_proto_censor_v1_censor_proto protoreflect.FileDescriptor

const file_api_proto_censor_v1_censor_proto_rawDesc = "" +
	"\n" +
	" api/proto/censor/v1/censor.proto\x12\tcensor.v1\"#\n" +
	"\rFilterRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xe4\x01\n" +
	"\x0eFilterResponse\x12\x1a\n" +
	"\boriginal\x18\x01 \x01(\tR\boriginal\x12\x1a\n" +
	"\bfiltered\x18\x02 \x01(\tR\bfiltered\x12\x15\n" +
	"\x06is_hit\x18\x03 \x01(\bR\x05isHit\x12\x1b\n" +
	"\thit_count\x18\x04 \x01(\x05R\bhitCount\x12.\n" +
	"\amatches\x18\x05 \x03(\v2\x14.censor.v1.MatchItemR\amatches\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x06 \x01(\x05R\triskLevel\x12\x17\n" +
	"\acost_ms\x18\a \x01(\x03R\x06costMs\"\x90\x01\n" +
	"\tMatchItem\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\x12!\n" +
	"\fend_position\x18\x03 \x01(\x05R\vendPosition\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\"*\n" +
	"\x12BatchFilterRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"y\n" +
	"\x13BatchFilterResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.censor.v1.FilterResponseR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x17\n" +
	"\ahit_num\x18\x03 \x01(\x05R\x06hitNum2\xdc\x01\n" +
	"\rCensorService\x12=\n" +
	"\x06Detect\x12\x18.censor.v1.FilterRequest\x1a\x19.censor.v1.FilterResponse\x12>\n" +
	"\aReplace\x12\x18.censor.v1.FilterRequest\x1a\x19.censor.v1.FilterResponse\x12L\n" +
	"\vBatchDetect\x12\x1d.censor.v1.BatchFilterRequest\x1a\x1e.censor.v1.BatchFilterResponseB=Z;github.com/bhrajate/censorhub/api/proto/censor/v1;censorv1b\x06proto3"

var (
	file_api_proto_censor_v1_censor_proto_rawDescOnce sync.Once
	file_api_proto_censor_v1_censor_proto_rawDescData []byte
)

func file_api_proto_censor_v1_censor_proto_rawDescGZIP() []byte {
	file_api_proto_censor_v1_censor_proto_rawDescOnce.Do(func() {
		file_api_proto_censor_v1_censor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_censor_v1_censor_proto_rawDesc), len(file_api_proto_censor_v1_censor_proto_rawDesc)))
	})
	return file_api_proto_censor_v1_censor_proto_rawDescData
}

var file_api_proto_censor_v1_censor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_censor_v1_censor_proto_goTypes = []any{
	(*FilterRequest)(nil),       // 0: censor.v1.FilterRequest
	(*FilterResponse)(nil),      // 1: censor.v1.FilterResponse
	(*MatchItem)(nil),           // 2: censor.v1.MatchItem
	(*BatchFilterRequest)(nil),  // 3: censor.v1.BatchFilterRequest
	(*BatchFilterResponse)(nil), // 4: censor.v1.BatchFilterResponse
}
var file_api_proto_censor_v1_censor_proto_depIdxs = []int32{
	2, // 0: censor.v1.FilterResponse.matches:type_name -> censor.v1.MatchItem
	1, // 1: censor.v1.BatchFilterResponse.results:type_name -> censor.v1.FilterResponse
	0, // 2: censor.v1.CensorService.Detect:input_type -> censor.v1.FilterRequest
	0, // 3: censor.v1.CensorService.Replace:input_type -> censor.v1.FilterRequest
	3, // 4: censor.v1.CensorService.BatchDetect:input_type -> censor.v1.BatchFilterRequest
	1, // 5: censor.v1.CensorService.Detect:output_type -> censor.v1.FilterResponse
	1, // 6: censor.v1.CensorService.Replace:output_type -> censor.v1.FilterResponse
	4, // 7: censor.v1.CensorService.BatchDetect:output_type -> censor.v1.BatchFilterResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_censor_v1_censor_proto_init() }
func file_api_proto_censor_v1_censor_proto_init() {
	if File_api_proto_censor_v1_censor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_censor_v1_censor_proto_rawDesc), len(file_api_proto_censor_v1_censor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_censor_v1_censor_proto_goTypes,
		DependencyIndexes: file_api_proto_censor_v1_censor_proto_depIdxs,
		MessageInfos:      file_api_proto_censor_v1_censor_proto_msgTypes,
	}.Build()
	File_api_proto_censor_v1_censor_proto = out.File
	file_api_proto_censor_v1_censor_proto_goTypes = nil
	file_api_proto_censor_v1_censor_proto_depIdxs = nil
}
